application:
  aws:
    sns:
      delete-placement-event:
        arn: dummy
      delete-programme-membership-event:
        arn: dummy
      update-conditions-of-joining:
        arn: dummy
        message-attribute: COJ_RECEIVED
      update-contact-details:
        arn: dummy
      update-gdc-details:
        arn: dummy
      update-gmc-details:
        arn: dummy
      update-person:
        arn: dummy
      update-person-owner:
        arn: dummy
      update-personal-info:
        arn: dummy
      update-placement-event:
        arn: dummy
      update-programme-membership-event:
        arn: dummy
    sqs:
      curriculum-membership: dummy
      placement: dummy
      placement-specialty: dummy
      post: dummy
      post-specialty: dummy
      profile-created: dummy
      programme: dummy
      programme-membership: dummy
      record: dummy
      request: dummy

mongock:
  enabled: false

spring:
  cloud:
    aws:
      region:
        static: eu-west-2
      sqs:
        enabled: false